config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    post '/comments' => 'comments#create', as: 'comments'
  end
  resources :actors do
     post '/comments' => 'comments#create', as: 'comments'
  end

  post '/movies/:id/actors/new' => 'movies#add_actor', as: :add_actor
  delete 'movies/:id/actors/:actor_id' => 'movies#remove_actor', as: :remove_actor

  post '/actors/:id/movies/new' => 'actors#add_movie', as: :add_movie
  delete '/actors/:id/movies/:movie_id' => 'actors#remove_movie', as: :remove_movie

  root 'site#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :actors_movies, dependent: :destroy
  has_many :movies, through: :actors_movies
  has_many :comments, as: :commentable
end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # validates :, presence: true
  belongs_to :commentable, polymorphic: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :actors_movies, dependent: :destroy
  has_many :actors, through: :actors_movies
  has_many :comments, as: :commentable

  validates :title, :presence => true
  validates :year, {
              :presence => true,
              :numericality => {
                :greater_than_or_equal_to => 1000,
                :less_than_or_equal_to => 3000
              }
            }
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :find_actor, only: [:edit, :show, :update, :destroy, :add_movie, :remove_movie]

  def index
    @actors = Actor.all

  end

  def create
    binding.pry
    Actor.create actor_params
    redirect_to actors_path
  end

  def new
    @actor = Actor.new
  end

  def edit
  end

  def show
    @movies = Movie.all - @actor.movies
    @comments = @actor.comments
  end

  def update
    @actor.update_attributes actor_params
    redirect_to @actor
  end

  def destroy
    @actor.destroy
    redirect_to actors_path
  end

  def add_movie
    @actor = Actor.find(params[:id])
    movie = Movie.find(movie_params[:id])
    unless @actor.movies.include? movie
      @actor.movies << movie
    end
    redirect_to @actor
  end

  def remove_movie
    movie = Movie.find(params[:movie_id])
    @actor.movies.delete(movie)
    redirect_to @actor
  end

  private
  def movie_params
    params.require(:movie).permit(:id, :title, :year)
  end

  def actor_params
    params.require(:actor).permit(:id, :name)
  end

  def find_actor
    @actor = Actor.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def create
    @commentable = find_commentable
    @comments = @commentable.comments
    @comment = Comment.new params.require(:comment).permit(:content) #comment.content: "   "
    if @comment.save
      @commentable.comments << @comment
      flash[:notice] = "Successfully saved comment."
      redirect_to @commentable
    else
      p @comment
      redirect_to @commentable
    end

  end

  def find_commentable
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:edit, :show, :destroy, :add_actor, :remove_actor]

  def index
    @movies = Movie.all
  end

  def create
    Movie.create movie_params
    redirect_to movies_path
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def show
    @actors = Actor.all - @movie.actors
     @comments = @movie.comments
  end

  def update
    @movie.update_attributes movie_params
    redirect_to @movie
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  def add_actor
    actor = Actor.find(actor_params[:id])
    unless @movie.actors.include? actor
      @movie.actors << actor
    end
    redirect_to @movie
  end

  def remove_actor
    @movie.actors.delete(Actor.find(params[:actor_id]))
    redirect_to @movie
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :year)
  end

  def actor_params
    params.require(:actor).permit(:id, :name)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @actors = Actor.all
    @movies = Movie.all
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/actors/edit.html.erb
<h1>Actors#edit</h1>
<p>Find me in app/views/actors/edit.html.erb</p>

app/views/actors/index.html.erb
<h1>Actors#index</h1>
<p>Find me in app/views/actors/index.html.erb</p>

app/views/actors/new.html.erb
<h1>Actors#new</h1>
<p>Find me in app/views/actors/new.html.erb</p>

app/views/actors/show.html.erb
<h1>Actors#show</h1>
<p>Find me in app/views/actors/show.html.erb</p>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p><%= @movie.year %></p>

<div class="black-box">
  <h2>Actors</h2>
  <ul>
    <% @movie.actors.each do |actor| %>
    <li>
      <%= link_to actor.name, actor %>
      <%= button_to "X", remove_actor_path(@movie, actor), :method => :delete %>
    </li>
    <% end %>
  </ul>
  <% unless @actors.empty? %>
    <%= form_tag add_actor_path(@movie) do %>
      <%= collection_select :actor, :id, @actors, :id, :name %>
      <%= submit_tag "Add" %>
    <% end %>
  <% end %>
</div>

<%= link_to "Edit", edit_movie_path(@movie) %>
<%= button_to "Delete", movie_path(@movie), :method => :delete %>
<br><br>

<%= link_to "Back to movies", movies_path %>


<h1>Comments</h1>


  <% @comments.each do |comment| %>
    <li><%= comment.content %></li>
  <% end %>


<h2>Add a new Comment!</h2>
<%= form_for [@movie, Comment.new] do |form| %>
<!--   <ol class="formList"> -->
      <%= form.label :content %>
      <%= form.text_area :content, :rows => 5 %>

   <%= form.submit "Add comment" %>
<!--   </ol> -->
<% end %>

app/views/site/index.html.erb
<h1>Check out all these Movies/ Actors</h1>
<p>Find me in app/views/site/index.html.erb</p>